#!/usr/bin/env python3
"""Rewrite the 6 MINDS block on the home page (index.html) from .moai/project/six-minds-data.json.

Funnel role (top of funnel): one promise ("get your own card"), one primary CTA (4-minute test),
a flippable card that shows a labelled sample back before the test and the visitor's own back after it,
and the six colour characters that open each mind's signals.

The block sits between <!-- 6MINDS:START --> and <!-- 6MINDS:END -->.
Re-run after editing the data:  python3 scripts/build-home-minds.py
"""
import html, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
M = json.loads((ROOT / '.moai/project/six-minds-data.json').read_text(encoding='utf-8'))
BY = {m['k']: m for m in M}
IMG = {'explorer': (76, 80), 'maker': (71, 76), 'connector': (74, 71), 'supporter': (71, 70), 'thinker': (63, 80), 'enjoyer': (85, 67)}
esc = lambda s: html.escape(s, quote=True)


def chips():
    out = ''
    for m in M:
        w, h = IMG[m['k']]
        out += (f'        <li class="types__i types__i--{m["k"]}"><a href="/diagnosis/minds/#{m["k"]}" data-mind="{m["k"]}" aria-controls="mind-{m["k"]}" aria-expanded="false" '
                f'aria-label="{esc(m["char"])}, {esc(m["n"])} 설명 보기"><img src="/assets/brand/type-{m["k"]}.png" width="{w}" height="{h}" alt="" loading="lazy">'
                f'<strong>{esc(m["char"])}</strong><span>{esc(m["n"])}</span></a></li>\n')
    return out


def panels():
    out = ''
    for m in M:
        p = BY[m['pair_k']]
        out += f'''        <div class="types__p" id="mind-{m['k']}" data-mind="{m['k']}" style="--mc:{m['c']};" hidden>
          <div class="types__pimg"><img src="/assets/brand/char-{m['k']}.jpg" width="520" height="520" alt="{esc(m['char'])}, {esc(m['n'])}을 그린 캐릭터" loading="lazy"><p class="types__pq">&ldquo;{esc(m['q'])}&rdquo;</p></div>
          <div class="types__pb">
            <p class="types__pk">{m['en']} · {esc(m['char'])}</p>
            <h3 class="types__pt">{esc(m['n'])}<span class="dot">.</span></h3>
            <p class="types__pd">{esc(m['d'])}</p>
            <p class="types__ps"><b>언제 힘이 나나</b> {esc(m['src'])}</p>
            <ul class="types__sig">
              <li class="types__sig--on"><b>잘 쓰고 있을 때</b><span>{esc(m['on'])}</span></li>
              <li class="types__sig--low"><b>거의 안 쓸 때</b><span>{esc(m['low'])}</span></li>
              <li class="types__sig--over"><b>지나치게 쓸 때</b><span>{esc(m['over'])}</span></li>
            </ul>
            <p class="types__pi"><b>자세히 보면</b> {esc(m['ins'])}</p>
            <p class="types__pair"><b>짝이 되는 마음</b> <a href="#mind-{p['k']}" data-mind-jump="{p['k']}">{esc(p['n'])}</a> · {esc(m['pair_w'])}</p>
            <div class="types__pa"><p><b>이 마음을 더 쓰고 싶을 때</b> {esc(m['more'])}</p><p><b>이 마음을 줄여야 할 때</b> {esc(m['less'])}</p></div>
            <p class="types__pl"><a class="btn-dark" href="/diagnosis/minds/">4분 진단하고 내 카드 받기</a><a class="btn-link" href="/minds/#colors">여섯 색 캐릭터 보기 &#8599;</a></p>
          </div>
        </div>
'''
    return out


BLOCK = f'''<!-- 6MINDS:START (generated by scripts/build-home-minds.py) -->
    <div class="types">
      <div class="types__hook">
        <div class="types__hookt">
          <p class="types__kick"><b>6 MINDS</b> 무료 · 15문항 · 약 4분</p>
          <h2 class="types__h">지난 2주, 나는 어느 마음을 가장 많이 썼을까</h2>
          <p class="types__lead">진단을 마치면 여섯 마음 카드 여섯 장이 모두 내 결과로 만들어집니다. 뒷면마다 <b>그 마음에 대한 내 수치와 해석</b>이 들어갑니다. 가장 많이 쓴 마음 한 장은 바로 열리고, 친구나 단톡방에 한 번 공유하면 여섯 장이 모두 열립니다. 카드를 누르면 뒷면 예시가 보입니다.</p>
          <p class="types__cta"><a class="btn-go" href="/diagnosis/minds/">4분 진단하고 내 카드 받기</a></p>
          <p class="types__meta">가입 없음 · 결과는 저장하지 않음 · 팀·학급·공동체와 함께 하려면 <a href="/minds/#invite">제주 방문 프로그램 안내</a></p>
          <p class="types__meta" id="homeBoxLink" hidden><a href="/minds/box/">2주 안에 받은 내 카드함 열기 &#8599;</a></p>
        </div>
        <div class="types__card" id="homeCard"></div>
      </div>
      <p class="types__head"><b>여섯 색 캐릭터</b> 캐릭터를 누르면 그 마음의 신호와 이번 주 행동이 아래에 나옵니다.</p>
      <ul class="types__list">
{chips()}      </ul>
      <div class="types__panel" aria-live="polite">
{panels()}      </div>
    </div>
    <!-- 6MINDS:END -->'''

SCRIPT = '''<script src="/assets/mind-data.js" defer></script>
<script src="/assets/mind-cards.js" defer></script>
<script>document.addEventListener('DOMContentLoaded',function(){ var h=document.getElementById('homeCard'); if(!h||!window.NWCards) return; var ch=''; NWCards.MINDS.forEach(function(m){ if(m.k==='enjoyer') ch=m.char; }); NWCards.card(h,{k:'enjoyer',title:'예시 카드 · '+ch}); var b=NWCards.lastBox(), l=document.getElementById('homeBoxLink'); if(b&&l){ l.hidden=false; l.querySelector('a').href=b.url; } });</script>
'''

p = ROOT / 'index.html'
s = p.read_text(encoding='utf-8')
if '<!-- 6MINDS:START' in s:
    s = re.sub(r'<!-- 6MINDS:START.*?<!-- 6MINDS:END -->', lambda _: BLOCK, s, count=1, flags=re.S)
else:  # first run: replace the hand-written block
    i = s.index('    <div class="types">')
    j = s.index('<!-- ===== FREE DIAGNOSIS ===== -->')
    tail = s[i:j]
    k = tail.index('      </div>\n    </div>\n') + len('      </div>\n    </div>\n')
    s = s[:i] + '    ' + BLOCK + '\n' + s[i + k:]
s = re.sub(r"<script>document\.addEventListener\('DOMContentLoaded',function\(\)\{ var h=document\.getElementById\('homeCard'\).*?</script>\n", lambda _: SCRIPT.split('\n')[2] + '\n', s, flags=re.S)
if '/assets/mind-cards.js' not in s:
    s = s.replace('<script src="/assets/sky.js" defer></script>', SCRIPT + '<script src="/assets/sky.js" defer></script>', 1)
if '/assets/mind-cards.css' not in s:
    s = s.replace('<link rel="stylesheet" href="/assets/sky.css">', '<link rel="stylesheet" href="/assets/sky.css">\n<link rel="stylesheet" href="/assets/mind-cards.css">', 1)
p.write_text(s, encoding='utf-8')
print('-> index.html 6 MINDS block')
