#!/usr/bin/env python3
"""Generate /minds/ — 6 MINDS 소개 페이지.

Mind copy comes from .moai/project/six-minds-data.json (same text as the home panel).
Re-run after editing:  python3 scripts/build-minds-page.py
"""
import importlib.util, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location('bd', ROOT / 'scripts' / 'build-diagnosis.py')
bd = importlib.util.module_from_spec(spec); spec.loader.exec_module(bd)
esc, head, HEADER, FOOTER, ARROW, SITE = bd.esc, bd.head, bd.HEADER, bd.FOOTER, bd.ARROW, bd.SITE

M = json.loads((ROOT / '.moai/project/six-minds-data.json').read_text(encoding='utf-8'))
COLOR = {m['k']: m['c'] for m in M}
# assets/mind-data.js: the same copy for assets/mind-cards.js (card backs are drawn in the browser)
READ = json.loads((ROOT / '.moai/project/six-minds-interpret.json').read_text(encoding='utf-8'))
(ROOT / 'assets' / 'mind-data.js').write_text('/* generated by scripts/build-minds-page.py from .moai/project/six-minds-data.json and six-minds-interpret.json — do not edit */\nwindow.NW_MINDS=' + json.dumps(M, ensure_ascii=False) + ';\nwindow.NW_READ=' + json.dumps(READ, ensure_ascii=False) + ';\n', encoding='utf-8')
URL = f'{SITE}/minds/'
TITLE = '6 MINDS · 서로 다른 6가지 마음이, 하나의 세상을 만듭니다 | 네다바웨이'
DESC = '지난 2주, 나는 어느 마음을 가장 많이 썼을까. 15문항 4분 진단을 마치면 앞면에는 내 색 캐릭터, 뒷면에는 내 에너지 총량과 여섯 마음 배분, 이번 주 줄일 마음과 늘릴 마음이 담긴 나만의 마음 카드를 받습니다. 팀·학급·공동체 워크숍 안내.'

def colors():
    out = ''
    for i, m in enumerate(M):
        out += f'''<button type="button" class="mp-color" data-open-card="{m['k']}" style="--mc:{m['c']};"><span class="mp-color__sw"><img src="/assets/brand/char-{m['k']}.jpg" width="520" height="520" alt="" loading="lazy"></span><span class="mp-color__b"><span class="mp-color__k">0{i+1} · {m['en']} · {m['c']}</span><b>{esc(m['char'])}</b><span class="mp-color__n">{esc(m['n'])}</span><span class="mp-color__d">{esc(m['char_d'])}</span></span></button>'''
    return out

JSONLD = json.dumps({
 "@context": "https://schema.org", "@type": "WebPage", "name": "6 MINDS 소개", "url": URL, "inLanguage": "ko", "description": DESC,
 "about": {"@type": "Organization", "name": "네다바웨이 NEDABAHWAY", "url": SITE},
 "hasPart": [{"@type": "DefinedTerm", "name": m['n'], "description": m['d']} for m in M],
}, ensure_ascii=False)

PAGE = head(TITLE, DESC, URL, 'minds', f'<link rel="stylesheet" href="/assets/minds.css">\n<link rel="stylesheet" href="/assets/mind-cards.css">\n<script src="/assets/mind-data.js" defer></script>\n<script src="/assets/mind-cards.js" defer></script>\n<script type="application/ld+json">{JSONLD}</script>\n') + HEADER + f'''
<main id="main" class="mp">

  <section class="mp-hero">
    <div class="wrap mp-hero__grid">
      <div class="mp-hero__txt">
        <p class="mp-kicker"><span>6 Minds</span> Different People · Bigger World</p>
        <h1 class="mp-h1">지난 2주, 나는<br>어느 마음을<br>가장 많이 썼을까<span class="mp-dot" aria-hidden="true"></span></h1>
        <p class="mp-lead">탐험 · 만들기 · 연결 · 돕기 · 생각 · 즐기기. 누구나 여섯 마음을 <b>다</b> 갖고 있고, 사람마다 다른 것은 요즘 어느 마음을 얼마나 쓰는가입니다. 진단을 마치면 <b>내 결과가 뒷면에 담긴 마음 카드</b>를 받습니다.</p>
        <ul class="mp-hero__two">
          <li><b>앞면 · 모두 같음</b>그 2주 동안 내가 가장 많이 쓴 마음과 색 캐릭터. 인스타그램에 올리는 면입니다.</li>
          <li><b>뒷면 · 나만 다름</b>그 마음에 대한 내 수치(사용 지수·회복 지수·배분 비중·총량 기여)와 해석, 이번 주 한 가지. 여섯 장 모두 내 결과로 만들어지고, 내 기기에만 저장합니다.</li>
        </ul>
        <p class="mp-hero__cta"><a class="btn-go" href="/diagnosis/minds/">4분 진단하고 내 카드 받기 {ARROW}</a></p>
        <p class="mp-hero__meta">15문항 · 약 4분 · 가입 없음 · 결과는 내 기기에만</p>
      </div>
      <div class="mp-hero__card" id="mpHeroCard"></div>
    </div>
  </section>

  <section class="mp-colors" id="colors" aria-labelledby="colorsTitle">
    <div class="wrap">
      <p class="sec-kicker">Six colours</p>
      <h2 class="mp-h2" id="colorsTitle">여섯 마음, 여섯 색 캐릭터<span class="mp-dot" aria-hidden="true"></span></h2>
      <p class="mp-lead">마음의 이름은 그대로 두고, 마음마다 색 이름을 붙인 캐릭터를 만들었습니다. 즐기는 마음의 캐릭터는 <b>즐기는 핑크</b>입니다. 캐릭터를 누르면 그 마음의 카드를 봅니다.</p>
      <div class="mp-colors__g">{colors()}</div>
    </div>
  </section>

  <section class="mp-scene" id="why">
    <div class="wrap">
      <p class="sec-kicker">Why now</p>
      <h2 class="mp-h2">이런 순간, 있지 않나요<span class="mp-dot" aria-hidden="true"></span></h2>
      <div class="mp-scene__g">
        <article class="mp-scene__c" style="--mc:#3B82F6;"><p class="mp-scene__who">팀장 · 관리자</p><p class="mp-scene__q">"팀원이 일은 다 하는데 표정이 어둡고 말수가 줄었다. 면담에서는 '괜찮아요'라는 대답만 듣는다."</p><p class="mp-scene__a">6 MINDS는 "괜찮아요" 대신 <b>"요즘 나는 만드는 마음을 지나치게 쓰고 즐기는 마음을 거의 안 쓴다"</b>는 문장을 줍니다. 리더와 팀원은 그 문장으로 대화를 시작합니다.</p></article>
        <article class="mp-scene__c" style="--mc:#FF6B3D;"><p class="mp-scene__who">교사 · 청소년</p><p class="mp-scene__q">"궁금한 게 없어요. 하고 싶은 것도요."</p><p class="mp-scene__a">무기력은 성향이 아니라 상태입니다. 탐험하는 마음을 거의 안 쓴 2주를 막대로 보여 주면, 학생은 자기 상태를 <b>처음으로 말로 설명합니다.</b> 말로 설명할 수 있으면 바꿀 수 있습니다.</p></article>
        <article class="mp-scene__c" style="--mc:#10B981;"><p class="mp-scene__who">공동체 · 소그룹 리더</p><p class="mp-scene__q">"열심히 섬기는 사람이 먼저 지쳐서 떠난다."</p><p class="mp-scene__a">돕는 마음을 지나치게 쓰는 사람은 자기 힘이 다 떨어져도 잘 알아차리지 못합니다. 서로의 배분을 나란히 놓으면 <b>누가 누구에게 힘이 되는지</b> 보입니다.</p></article>
        <article class="mp-scene__c" style="--mc:#F472B6;"><p class="mp-scene__who">나 자신</p><p class="mp-scene__q">"쉬어도 쉰 것 같지 않다."</p><p class="mp-scene__a">에너지 총량의 60%는 잠·움직임·의욕에서 나옵니다. 더 열심히 하기보다 <b>나를 지치게 하는 것을 먼저 줄이는 것</b>이 순서입니다. 4분이면 어느 마음이 나를 지치게 하는지 나옵니다.</p></article>
      </div>
    </div>
  </section>

  <section class="mp-why">
    <div class="wrap mp-why__in">
      <div>
        <p class="sec-kicker">Why minds, not types</p>
        <h2 class="mp-h2">성향 검사와<br>무엇이 다른가<span class="mp-dot" aria-hidden="true"></span></h2>
        <p class="mp-why__lead">MBTI, DISC, HEXACO, 에니어그램은 좋은 도구입니다. 그런데 한 번 알면 끝이고, 오늘 무엇을 바꿀지는 말해 주지 않습니다. 6 MINDS는 <b>지금의 상태</b>를 보고, <b>이번 주 한 가지</b>를 줍니다.</p>
      </div>
      <ul class="mp-why__l">
        <li><b>라벨을 붙이지 않습니다</b>"너는 탐험하는 사람"은 판정이라 듣는 사람이 방어하게 됩니다. "요즘 너는 탐험하는 마음을 많이 쓰고 있네"는 관찰이라 받아들이기 쉽습니다.</li>
        <li><b>다시 해 볼 이유가 있습니다</b>성향은 잘 안 바뀌지만 상태는 2주 단위로 바뀝니다. 4주 뒤 다시 해 보면 "이걸 더 하려고 저걸 줄여 왔구나"가 보이고, 새 카드를 받을 수도 있습니다.</li>
        <li><b>처방이 곧바로 나옵니다</b>지나치게 쓰는 마음 하나를 줄이고, 거의 안 쓰는데 힘이 나는 마음 하나를 늘리는 것. 코스 여섯 개가 필요 없고 이번 주 한 가지면 됩니다.</li>
        <li><b>총량이 보입니다</b>여섯 마음을 쓰고 나서 힘이 나는지 지치는지를 따로 묻기 때문에, 에너지 총량이 어디쯤인지와 어느 마음이 나를 지치게 하는지가 나옵니다.</li>
      </ul>
    </div>
  </section>

  <section class="mp-flow">
    <div class="wrap">
      <p class="sec-kicker">One diagnosis, four weeks</p>
      <h2 class="mp-h2">한 번의 진단, 4주의 변화<span class="mp-dot" aria-hidden="true"></span></h2>
      <ol class="mp-flow__l">
        <li style="--mc:#FF6B3D;"><b>15문항, 4분</b>지난 2주를 떠올리며 고릅니다. 회원가입 없음, 답은 내 기기에만 남습니다.</li>
        <li style="--mc:#F472B6;"><b>내 결과 카드 여섯 장</b>가장 많이 쓴 마음 한 장은 바로 열리고, 한 번 공유하면 나머지 다섯 장도 열립니다.</li>
        <li style="--mc:#FFC857;"><b>해설지</b>네 자리(지킬·줄일·늘릴·기다릴 마음), 요즘의 패턴, 총량을 키우는 네 가지.</li>
        <li style="--mc:#3B82F6;"><b>나란히 보기</b>코드를 주고받으면 두 사람의 배분이 나란히 나오고, 서로를 이해하는 문장이 붙습니다.</li>
        <li style="--mc:#8B5CF6;"><b>4주 뒤 다시</b>결과는 저장하지 않으므로, 4주 뒤에는 그때의 2주로 새 카드함을 받습니다. 코드를 적어 두면 두 시기를 나란히 봅니다.</li>
      </ol>
    </div>
  </section>

  <section class="mp-how" id="how">
    <div class="wrap">
      <p class="sec-kicker">How it works</p>
      <h2 class="mp-h2">어떻게 진단하나<span class="mp-dot" aria-hidden="true"></span></h2>
      <ol class="mp-how__l">
        <li><b>6개 마음</b>마음마다 "지난 2주 얼마나 썼나"(사용량)와 "쓰고 나면 힘이 나나, 지치나"를 따로 묻습니다.</li>
        <li><b>총량 3문항</b>잠 · 움직임 · 의욕. 총량의 60%는 여기서, 40%는 여섯 마음을 쓰고 난 뒤의 상태에서 옵니다.</li>
        <li><b>네 자리</b>많이 쓰고 힘이 나면 <b>지킬 마음</b>, 많이 쓰고 지치면 <b>줄일 마음</b>, 적게 쓰는데 힘이 나면 <b>늘릴 마음</b>, 적게 쓰고 지치면 <b>기다릴 마음</b>.</li>
        <li><b>차이 지수</b>가장 많이 쓴 마음과 가장 적게 쓴 마음의 차이. 한쪽 마음만 많이 썼는지, 고르게 썼는지를 한 숫자로 봅니다.</li>
        <li><b>트레이드오프 문장</b>"이걸 더 하려고 저걸 줄여 왔구나." 판정이 아니라 관찰의 언어입니다.</li>
        <li><b>여덟 자리와 네 수치</b>마음마다 사용 지수·회복 지수·배분 비중·총량 기여를 계산하고, 지킬·줄일·늘릴·기다릴·키울·살필·유지할·다시 써 볼 마음 여덟 자리로 해석합니다. <a href="/minds/method/">설계 근거 보기</a></li>
      </ol>
      <p class="mp-note">우울·불안 같은 단어를 쓰지 않고, 총량이 30 미만이면 상담전화를 조용히 안내합니다. 개인 결과는 본인에게만, 기관에는 평균과 총량 변화만 갑니다. 네다바웨이가 직접 설계한 상태 진단 도구이며, 기관 성과 측정에는 표준화 척도를 함께 씁니다.</p>
    </div>
  </section>

  <section class="mp-invite" id="invite">
    <div class="wrap">
      <p class="sec-kicker">For teams, classes, communities</p>
      <h2 class="mp-h2">혼자 받은 카드를<br>팀이 함께 읽으면<span class="mp-dot" aria-hidden="true"></span></h2>
      <p class="mp-lead">진단은 누구나 무료로 혼자 할 수 있습니다. 제주 방문 프로그램에서는 진행자가 구성원 한 사람 한 사람의 카드 뒷면을 이름 없이 모아 <b>한 장의 팀 배분 지도</b>로 만듭니다. 우리 팀이 어느 마음을 많이 쓰고 어느 마음을 거의 안 쓰는지, 혼자서는 볼 수 없는 모습이 나옵니다. 리더는 팀원의 상태를 물을 수 있는 <b>문장</b>을, 기관은 4주 뒤 변화를 숫자로 보는 <b>리포트</b>를 받습니다.</p>
      <div class="mp-invite__g">
        <article class="mp-invite__c" style="--mc:#FF6B3D;"><p class="mp-invite__k">90분 특강</p><h3>여섯 마음 첫 만남</h3><dl><dt>대상</dt><dd>전 직원 · 전 학년 · 교인, 인원 제한 없음</dd><dt>구성</dt><dd>진단 15분 → 카드 받기 → 해설 → 짝 대화</dd><dt>남는 것</dt><dd>한 사람당 내 결과 카드 한 장과 해설지</dd></dl></article>
        <article class="mp-invite__c" style="--mc:#3B82F6;"><p class="mp-invite__k">반나절 워크숍</p><h3>나란히 보기</h3><dl><dt>대상</dt><dd>팀 · 학급 · 소그룹 8~30명</dd><dt>구성</dt><dd>진단 → 카드 비교 → 팀 배분 지도 읽기 → 이번 주 한 가지 선언 → 리더 세션 30분</dd><dt>남는 것</dt><dd>팀 배분 지도, 리더 대화 가이드, 개인 카드와 해설지</dd></dl></article>
        <article class="mp-invite__c" style="--mc:#10B981;"><p class="mp-invite__k">4주 과정</p><h3>총량이 오르는 4주</h3><dl><dt>대상</dt><dd>같은 팀 · 학급 · 공동체 8~20명</dd><dt>구성</dt><dd>주 1회 90분 × 4회 + 재진단</dd><dt>남는 것</dt><dd>개인 4주 비교, 기관 리포트(평균 · 총량 변화 · 줄일 마음이 있는 사람 수), 워크숍 키트</dd></dl></article>
      </div>
      <div class="mp-invite__row">
        <div class="mp-invite__box"><b>강사가 하는 일</b><p>해설, 짝 대화 진행, 팀 배분 지도 작성, 리더 코칭, 기관 리포트. 12년 1,200회 교육현장과 ICF 인증 코칭 300시간의 방법으로 진행합니다.</p></div>
        <div class="mp-invite__box"><b>개인정보</b><p>개인 결과는 본인에게만 갑니다. 팀 배분 지도와 기관 리포트에는 이름 없이 평균과 분포만 들어가고, 이름이 붙은 결과는 어디에도 남지 않습니다.</p></div>
        <div class="mp-invite__box"><b>대상별 제안서</b><p><a href="/proposal/business/">기업·조직</a> · <a href="/proposal/institution/">기관·센터</a> · <a href="/proposal/faith/">신앙공동체</a> · <a href="/proposal/smallgroup/">소그룹·동아리</a>. 자발성 5단계와 6 MINDS를 엮은 10쪽 제안서입니다.</p></div>
      </div>
      <p class="mp-cta__b"><a class="btn-dark" href="/contact.html#lecture">강의 · 워크숍 문의</a><a class="btn-link" href="/proposal/">제안서 먼저 보기 &#8599;</a></p>
    </div>
  </section>

  <section class="mp-cards" id="cards">
    <div class="wrap">
      <p class="sec-kicker">Mind cards</p>
      <h2 class="mp-h2">진단 한 번에 여섯 장,<br>공유 한 번이면 모두 열립니다<span class="mp-dot" aria-hidden="true"></span></h2>
      <p class="mp-lead">진단을 마치면 여섯 마음 카드 여섯 장이 모두 <b>내 결과로</b> 만들어집니다. 가장 많이 쓴 마음 카드 한 장은 바로 열리고, 나머지 다섯 장은 잠겨 있습니다. 카카오톡 단톡방이나 친구에게 6 MINDS를 한 번 공유하면 다섯 장이 모두 무료로 열립니다. 결제는 받지 않고, 보내는 글에는 내 결과가 들어가지 않습니다.</p>
      <p class="mp-lead">결과는 저장하지 않습니다. 마음의 상태는 2주 단위로 바뀌기 때문에 새로 고침하면 결과 화면은 사라지고, 내가 보관한 <b>카드함 주소</b>로만 다시 엽니다. 카드는 앞면·뒷면 두 장을 휴대폰 화면 크기(1080×1920)로 사진첩에 저장합니다.</p>
      <div id="mpBoxLink"></div>
      <div id="mpCardView" hidden></div>
      <p class="mp-note">실물 카드 덱(36장)은 <a href="/goods/deck/">굿즈</a>에서 주문합니다.</p>
    </div>
  </section>
<script>document.addEventListener('DOMContentLoaded',function(){{ if(!window.NWCards) return; var view=document.getElementById('mpCardView'), hero=document.getElementById('mpHeroCard'), bl=document.getElementById('mpBoxLink'); var CH={{}}; NWCards.MINDS.forEach(function(m){{ CH[m.k]=m.char; }}); NWCards.card(hero,{{k:'enjoyer',title:'예시 카드 · '+CH.enjoyer}}); var b=NWCards.lastBox(); if(b){{ var bp=document.createElement('p'); bp.className='mp-boxlink'; bp.textContent='2주 안에 받은 내 카드함이 있습니다. '; var ba=document.createElement('a'); ba.className='btn-dark'; ba.textContent='내 카드함 열기'; ba.href=b.url; bp.appendChild(ba); bl.appendChild(bp); }} var show=function(k){{ view.hidden=false; NWCards.card(view,{{k:k,title:'미리 보기 · '+CH[k]}}); view.scrollIntoView({{behavior:'smooth',block:'center'}}); }}; document.querySelectorAll('[data-open-card]').forEach(function(a){{ a.addEventListener('click',function(){{ show(a.getAttribute('data-open-card')); }}); }}); }});</script>

  <section class="mp-use">
    <div class="wrap">
      <p class="sec-kicker">Where it lives</p>
      <h2 class="mp-h2">6 MINDS가 쓰이는 곳<span class="mp-dot" aria-hidden="true"></span></h2>
      <div class="mp-use__g">
        <a class="mp-use__c" href="/diagnosis/minds/" style="--mc:#FF6B3D;"><span class="mp-use__k">01 · 무료진단</span><b>요즘 나의 여섯 마음</b><p>15문항 4분. 내 결과 카드와 해설지, 이번 주 한 가지까지.</p><span class="mp-use__go">지금 해 보기 {ARROW}</span></a>
        <a class="mp-use__c" href="#invite" style="--mc:#3B82F6;"><span class="mp-use__k">02 · 프로그램</span><b>학교 · 기관 · 기업 교육</b><p>첫날과 마지막 날 같은 진단. 개인에게는 카드와 해설지, 기관에는 팀 배분 지도와 총량 변화.</p><span class="mp-use__go">프로그램 보기 {ARROW}</span></a>
        <a class="mp-use__c" href="/proposal/" style="--mc:#10B981;"><span class="mp-use__k">03 · 제안서</span><b>자립은 자발성에서 시작된다</b><p>자발성 5단계와 6 MINDS를 엮은 고객 유형별 제안서 4종.</p><span class="mp-use__go">제안서 열기 {ARROW}</span></a>
        <a class="mp-use__c" href="/goods/" style="--mc:#F472B6;"><span class="mp-use__k">04 · 굿즈</span><b>여섯 색 캐릭터 굿즈</b><p>스티커, 엽서, 포스터, 마음 카드 덱, 4주 노트, 워크숍 키트.</p><span class="mp-use__go">굿즈 보기 {ARROW}</span></a>
      </div>
    </div>
  </section>

  <section class="mp-cta">
    <div class="wrap">
      <h2 class="mp-h2">지난 2주, 나는 어느 색이었을까<span class="mp-dot" aria-hidden="true"></span></h2>
      <p class="mp-cta__b"><a class="btn-go" href="/diagnosis/minds/">4분 진단하고 내 카드 받기 {ARROW}</a><a class="btn-link" href="#invite">우리 팀과 함께 하려면 &#8599;</a></p>
    </div>
  </section>

</main>
''' + FOOTER


out = ROOT / 'minds' / 'index.html'; out.parent.mkdir(exist_ok=True)
out.write_text(PAGE, encoding='utf-8'); print('->', out.relative_to(ROOT))

# /minds/box/ — private card box. Opened only by the owner's box address (#r=code&d=day&i=ref&k=key); never indexed.
BOX = head('내 카드함 · 6 MINDS | 네다바웨이', '이번 진단으로 만든 여섯 장의 마음 카드. 한 번 공유하면 잠긴 다섯 장이 모두 열립니다.', f'{SITE}/minds/box/', 'minds',
  '<meta name="robots" content="noindex,nofollow">\n<link rel="stylesheet" href="/assets/minds.css">\n<link rel="stylesheet" href="/assets/mind-cards.css">\n'
  '<script src="/assets/mind-data.js" defer></script>\n<script src="/assets/mind-cards.js" defer></script>\n') + HEADER + f'''
<main id="main" class="mp">
  <section class="mp-cards" style="border-top:0;">
    <div class="wrap" style="max-width:860px;">
      <p class="sec-kicker">My card box</p>
      <h1 class="mp-h2">내 카드함<span class="mp-dot" aria-hidden="true"></span></h1>
      <p class="mp-lead" id="mbLead">이 주소는 나만 여는 카드함입니다. 주소에 내 진단 결과가 들어 있으니 다른 사람에게는 공유 버튼으로 초대 글만 보내세요.</p>
      <div id="mbBox"></div>
      <div id="mbRead" class="mr-list"></div>
      <p class="mp-cta__b"><a class="btn-go" href="/diagnosis/minds/">새로 진단하기 {ARROW}</a><a class="btn-link" href="/minds/">6 MINDS 소개 &#8599;</a></p>
    </div>
  </section>
<script>document.addEventListener('DOMContentLoaded',function(){{ if(!window.NWCards) return; var o=NWCards.parseBox(location.hash), lead=document.getElementById('mbLead');
  if(!o){{ lead.textContent='카드함 주소가 맞지 않습니다. 진단을 마친 화면에서 「카드함 주소 보관하기」로 받은 주소 전체를 열어 주세요.'; return; }}
  var days=Math.floor((Date.now()-new Date(o.at).getTime())/86400000);
  if(days>=14) lead.textContent='이 카드함은 '+days+'일 전 진단입니다. 마음의 상태는 2주 단위로 바뀝니다. 카드는 그대로 볼 수 있지만, 지금의 나를 보려면 새로 진단하세요.';
  NWCards.box(document.getElementById('mbBox'),o);
  var r=NWCards.compute(o.a); document.getElementById('mbRead').innerHTML=NWCards.energyHTML(r)+'<h2 class="mp-h2" style="margin-top:40px;font-size:clamp(24px,3vw,32px);">여섯 마음 깊게 읽기</h2>'+NWCards.sorted(r).map(function(m,i){{ return NWCards.readingHTML(r,m.k,i===0); }}).join(''); }});</script>
</main>
''' + FOOTER
ob = ROOT / 'minds' / 'box' / 'index.html'; ob.parent.mkdir(parents=True, exist_ok=True)
ob.write_text(BOX, encoding='utf-8'); print('->', ob.relative_to(ROOT))

# /minds/method/ — 설계 백서 (source: .moai/project/six-minds-whitepaper.md, tiny Markdown subset → HTML)
def md_html(md):
    out, i, L = [], 0, md.split('\n')
    inl = lambda t: esc(t).replace('&quot;', '"')
    while i < len(L):
        ln = L[i]
        if not ln.strip(): i += 1; continue
        if ln.startswith('# '): i += 1; continue  # page title is the h1
        if ln.startswith('### '): out.append(f'<h3>{inl(ln[4:])}</h3>'); i += 1; continue
        if ln.startswith('## '):
            t = ln[3:]; sid = 'sec-' + str(len([o for o in out if o.startswith('<h2')]) + 1)
            out.append(f'<h2 id="{sid}">{inl(t)}</h2>'); i += 1; continue
        if ln.startswith('|'):
            rows = []
            while i < len(L) and L[i].startswith('|'): rows.append([c.strip() for c in L[i].strip('|').split('|')]); i += 1
            head_, body_ = rows[0], [r for r in rows[2:]]
            out.append('<div class="mp-paper__tw"><table><thead><tr>' + ''.join(f'<th scope="col">{inl(c)}</th>' for c in head_) + '</tr></thead><tbody>' + ''.join('<tr>' + ''.join(f'<td>{inl(c)}</td>' for c in r) + '</tr>' for r in body_) + '</tbody></table></div>'); continue
        if ln.startswith('- ') or (ln[:1].isdigit() and ln[1:3] == '. '):
            tag = 'ul' if ln.startswith('- ') else 'ol'; items = []
            while i < len(L) and (L[i].startswith('- ') or (L[i][:1].isdigit() and L[i][1:3] == '. ')):
                items.append(L[i].split(' ', 1)[1]); i += 1
            out.append(f'<{tag}>' + ''.join(f'<li>{inl(t)}</li>' for t in items) + f'</{tag}>'); continue
        para_ = []
        while i < len(L) and L[i].strip() and not L[i].startswith(('#', '|', '- ')) and not (L[i][:1].isdigit() and L[i][1:3] == '. '): para_.append(L[i]); i += 1
        out.append(f'<p>{inl(" ".join(para_))}</p>')
    return '\n'.join(out)

WP = (ROOT / '.moai/project/six-minds-whitepaper.md').read_text(encoding='utf-8')
toc = ''.join(f'<li><a href="#sec-{n+1}">{esc(t)}</a></li>' for n, t in enumerate(re.findall(r'^## (.+)$', WP, re.M)))
MDESC = '6 MINDS의 목적과 사명·비전·핵심가치, 이론 근거, 15문항과 수치 체계, 여덟 자리 해석, 한계와 검증 계획을 정리한 설계 백서입니다.'
METHOD = head('6 MINDS 설계 백서 | 네다바웨이', MDESC, f'{SITE}/minds/method/', 'minds', '<link rel="stylesheet" href="/assets/minds.css">\n') + HEADER + f'''
<main id="main" class="mp">
  <article class="mp-paper">
    <div class="wrap mp-paper__in">
      <p class="sec-kicker">Whitepaper · v1.0 · 2026. 9.</p>
      <h1 class="mp-h2">6 MINDS 설계 백서<span class="mp-dot" aria-hidden="true"></span></h1>
      <p class="mp-lead">요즘 나의 여섯 마음: 2주 단위 상태 기반 에너지 배분 진단의 목적, 이론, 측정, 해석, 한계</p>
      <nav class="mp-paper__toc" aria-label="목차"><b>목차</b><ol>{toc}</ol></nav>
      <div class="mp-paper__body">
{md_html(WP)}
      </div>
      <p class="mp-cta__b"><a class="btn-go" href="/diagnosis/minds/">4분 진단하고 내 카드 받기 {ARROW}</a><a class="btn-link" href="/minds/#invite">팀 워크숍 안내 &#8599;</a></p>
    </div>
  </article>
</main>
''' + FOOTER
om = ROOT / 'minds' / 'method' / 'index.html'; om.parent.mkdir(parents=True, exist_ok=True)
om.write_text(METHOD, encoding='utf-8'); print('->', om.relative_to(ROOT))
