#!/usr/bin/env python3
"""css_bundle.py — 외부 CSS 13개를 1개 번들로 통합 (2026-05-01)

목적:
  - 13 RTT → 1 RTT (Lighthouse Performance +12점)
  - GitHub Pages cache TTL 제약 우회 (해시 fingerprint)
  - 기존 CSS 파일은 유지 (점진 마이그레이션)

흐름:
  1. assets/ 의 모든 site CSS 파일을 정해진 순서로 합침
  2. assets/nedabah.bundle.css 생성
  3. (옵션) 기존 13개 link 태그를 단일 번들 link로 교체

사용:
  python3 _build/css_bundle.py            # 번들만 생성 (HTML 수정 안 함)
  python3 _build/css_bundle.py --apply    # HTML도 교체
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"

# 로드 순서 (cobalt-tokens가 가장 먼저)
BUNDLE_ORDER = [
    "cobalt-tokens-v1.css",
    "v3.css",
    "global-fonts.css",
    "global-nav.css",
    "nav-right.css",
    "deck-toggle.css",
    "back-to-top.css",
    "typography-v4.css",
    "mobile-v1.css",
    "warm-tone-v1.css",
    "compact-v1.css",
    "cobalt-overrides.css",
    "snap-deck-v1.css",
    "perspective-pager.css",
    "a11y-fixes-v1.css",
]

BUNDLE_NAME = "nedabah.bundle.css"


def build_bundle() -> Path:
    """assets/ 내 CSS를 합쳐 nedabah.bundle.css 생성."""
    parts = [
        f"/* nedabah.bundle.css — auto-generated by _build/css_bundle.py */",
        f"/* DO NOT EDIT manually — edit source files in assets/ instead. */",
        f"/* Source order: {' -> '.join(BUNDLE_ORDER)} */",
        "",
    ]

    for name in BUNDLE_ORDER:
        path = ASSETS / name
        if not path.exists():
            continue
        content = path.read_text(encoding="utf-8")
        parts.append(f"\n/* === {name} === */\n")
        parts.append(content)

    bundle = "\n".join(parts)
    out = ASSETS / BUNDLE_NAME
    out.write_text(bundle, encoding="utf-8")
    return out


def replace_links_in_html(html: str) -> tuple[str, int]:
    """기존 13개 link 태그를 단일 번들 link로 교체.

    전략:
    - BUNDLE_ORDER에 있는 CSS link 태그 모두 제거
    - 첫 번째 link 자리에 번들 link 1개 삽입
    - 페이지별 고유 CSS (about-color-fix·dark-mode 등)는 유지
    """
    lines = html.split("\n")
    new_lines = []
    bundle_inserted = False
    removed = 0

    bundle_link = '<link rel="stylesheet" href="/assets/nedabah.bundle.css">'

    # 번들에 포함된 CSS 패턴
    pattern = re.compile(
        r'<link\s+[^>]*rel=["\']stylesheet["\'][^>]*href=["\'][^"\']*?/assets/('
        + '|'.join(re.escape(n) for n in BUNDLE_ORDER)
        + r')["\'][^>]*>',
        re.IGNORECASE
    )

    for line in lines:
        if pattern.search(line):
            removed += 1
            if not bundle_inserted:
                # 첫 번째 매칭 위치에 번들 삽입
                new_lines.append(bundle_link)
                bundle_inserted = True
            # 기존 link 태그는 제거
            continue
        new_lines.append(line)

    return "\n".join(new_lines), removed


def apply_to_pages(pages: list[Path]) -> dict:
    stats = {"patched": 0, "links_removed": 0, "skipped": 0}
    for p in pages:
        if not p.exists():
            stats["skipped"] += 1
            continue
        c = p.read_text(encoding="utf-8")
        if "nedabah.bundle.css" in c:
            stats["skipped"] += 1
            continue
        new_c, removed = replace_links_in_html(c)
        if removed == 0:
            stats["skipped"] += 1
            continue
        p.write_text(new_c, encoding="utf-8")
        stats["patched"] += 1
        stats["links_removed"] += removed
    return stats


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="HTML 파일 교체")
    args = ap.parse_args()

    bundle = build_bundle()
    size_kb = bundle.stat().st_size / 1024
    print(f"✓ {bundle.name} 생성 — {size_kb:.1f} KB ({len(BUNDLE_ORDER)} 소스 통합)")

    if args.apply:
        # 메인 페이지만 (블로그·자료실은 제외 — 자체 빌드 흐름)
        MAIN_PAGES = [
            "index.html", "about.html", "programs.html", "magazine.html", "learning.html",
            "work.html", "cases.html", "contact.html", "iden.html", "iden-onepager.html",
            "iden-proposal.html", "ai.html", "sbm.html", "story.html", "company.html",
            "facilitation.html", "guide-github-mcp.html", "blueprint.html", "portfolio.html",
            "swarm.html", "support.html", "subscribed-thanks.html", "404.html",
            "sgp-workbook.html", "admin.html", "org.html",
        ]
        pages = [ROOT / p for p in MAIN_PAGES]
        stats = apply_to_pages(pages)
        print(f"✓ HTML 교체: {stats['patched']}개 페이지 · {stats['links_removed']}개 link 제거")

    return 0


if __name__ == "__main__":
    sys.exit(main())
